---
apiVersion: v1
kind: Namespace
metadata:
  name: kev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: kev
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest # Use official mongo image or ensure your custom image is correct
          imagePullPolicy: IfNotPresent
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
            - name: MONGO_INITDB_DATABASE
              value: "kev"
          volumeMounts:
            - name: mongo-data
              mountPath: "/data/db"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
---
